### ISSUE TITLE
globalize.format is not a function

### ISSUE THREAD

**Issue by willdady** [jquense/react-widgets#296]
I'm getting the error `globalize.format is not a function` when running a production build. I'm running globalize@1.1.0-rc.5

Looks like the error originates on line 177 of the globalize localiser. Is it possible the old vs new globalize check on line 29 is the issue, treating it as an older version rather than new?

**Comment by jquense** [comment]
I'll take a look but I know it works with other versions of 1.0.0, I don't think that they'd remove an api...Namely the `.load()` method it uses to sniff the globalize version

**Comment by jquense** [comment]
`.load` is still there, so i must have something to do with how or waht object you are passing to the localizer

**Comment by willdady** [comment]
```
var Globalize = require('globalize');
console.log(Globalize.load);
```
Checked myself and load exists when running dev but is `undefined` when running a production build. My webpack config is almost identical to this [official globalize example](https://github.com/jquery/globalize/blob/master/examples/app-npm-webpack/webpack-config.js).

**Comment by jquense** [comment]
interesting...looks like I need a better way to sniff. thanks for the heads up

**Comment by willdady** [comment]
Thanks. Are you treading <1.0.0 as **old** and 1.x as **new**? If so, you might be able to check for the presence of `Globalize.cultures`.

See https://github.com/jquery/globalize/blob/master/doc/migrating-from-0.x.md
