### ISSUE TITLE
Uncaught TypeError (0, y.default) is not a function

### ISSUE THREAD

**Issue by NA-Dev** [jquense/react-widgets#979]
Tying to update an old react project with your package installed. I get this console error with version 4.4.11. "Uncaught TypeError (0, y.default) is not a function"

Looks like because of the old version of uncontrollable required. When I update to 5 versions, uncontrollable is on a newer version and this error goes away. But instead I get the following during compile:

ERROR in ../node_modules/react-widgets/dist/css/react-widgets.css (../node_modules/css-loader/dist/cjs.js??ref--10-2!../node_modules/postcss-loader/src!../node_modules/react-widgets/dist/css/react-widgets.css)
    Module build failed (from ../node_modules/css-loader/dist/cjs.js):
    TypeError: Cannot read property 'slice' of undefined
